### ISSUE TITLE
Twitch counter

### ISSUE THREAD

**Issue by claudiosmweb** [claudiosmweb/social-count-plus#14]
Requests:

* http://wordpress.org/support/topic/twitch-integration?replies=5

**Comment by shinyidol** [comment]
This would be huge! Please revisit!

**Comment by winfreds** [comment]
@claudiosmweb any update on this?

**Comment by claudiosmweb** [comment]
@winfreds nop

**Comment by claudiosmweb** [comment]
I'll never add this!
