### ISSUE TITLE
Request: Instagram "follows" and "media" counts

### ISSUE THREAD

**Issue by zoerooney** [claudiosmweb/social-count-plus#20]
As a feature request, I would love the ability to display the other two counts the Instagram API provides in addition to the "followed_by" count (per http://instagram.com/developer/endpoints/users/#get_users): "follows" and "media." If I have a chance, I'll play around and see what I can do but I thought I'd post the request in case you have time/ interest in tackling this. Thanks!

**Comment by claudiosmweb** [comment]
we'll have just instagram followers
