### ISSUE TITLE
Facebook Counter not updated

### ISSUE THREAD

**Issue by spiritdetox** [claudiosmweb/social-count-plus#24]
I've just loaded the plug-in and installed and everything looks good; however the facebook counter is not updating automatically. In fact, it's not updating the new likes at all,

Here's a link to my site: http://quantumstones.com/crystals-get-lost-crystals-stones-want-rock-world/
If you click on the facebook icon, and go to my facebook page, you will notice the numbers on my facebook page are higher then my website numbers.

Not sure what to do? hope you can help ?

Thank you,
Albert

**Comment by claudiosmweb** [comment]
Tested and works fine.
