### ISSUE TITLE
Youtube Counter does'nt work anymore

### ISSUE THREAD

**Issue by vidzfromhell** [claudiosmweb/social-count-plus#28]
Hi, is there an issue with the yt-counter? He had stop counting, after checking the settings and deactivate/activate and setup up the channel name new he stays at zero.

Environment
Social Count Plus Version:	3.0.3
WordPress Version:	4.2.2
WP Multisite Enabled:	No
Web Server Info:	Apache/2.4.10
PHP Version:	5.5.14
fsockopen/cURL:	Your server has fsockopen and cURL enabled.
WP Remote Get:	wp_remote_get() failed. This may not work with your server.

**Comment by claudiosmweb** [comment]
I'll check soon.

**Comment by vidzfromhell** [comment]
I'm not the only one, a friend had the same problem.

**Comment by claudiosmweb** [comment]
Fixed in version 3.1.1.

**Comment by Dude77** [comment]
Thx.
