### ISSUE TITLE
Hi..

### ISSUE THREAD

**Issue by Neil2305** [claudiosmweb/social-count-plus#30]
I have only just notice that our Facebook counter is at 0
not sure what the problem is...
website is here
https://www.londontheatre1.com/

Facebook Page is here https://www.facebook.com/londontheatre1
with over 2700 Likes..

Any suggestions ? :)

Thanks Neil

**Comment by claudiosmweb** [comment]
Because you need to create an app on facebook and copy the right keys, see: https://www.youtube.com/watch?v=LgavLDh7GPA
